title: Learn! Learn.
author: Juyeon Yu
email: juyeon.yu@coway.com
description: > # this means to ignore newlines until "baseurl:"
  Learn. Header Meta data?

# social links
github_username: cw-juyeonyu

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
